// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqTt-6GbaSbXOJ_U9PtiEYMHlo5W5RtjA',
    appId: '1:106580139327:web:00eda5a58b1fabf33bc78a',
    messagingSenderId: '106580139327',
    projectId: 'therapy-app-9d5f9',
    authDomain: 'therapy-app-9d5f9.firebaseapp.com',
    storageBucket: 'therapy-app-9d5f9.firebasestorage.app',
    measurementId: 'G-GKLGHRSD3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4rIXSwVs7K13i6JR0E10Im4B0TUE1Qio',
    appId: '1:106580139327:android:5790499843469c9b3bc78a',
    messagingSenderId: '106580139327',
    projectId: 'therapy-app-9d5f9',
    storageBucket: 'therapy-app-9d5f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOmID1iif-2V00x3FRoILbvd92DJFJBFs',
    appId: '1:106580139327:ios:3373c22a68bc279d3bc78a',
    messagingSenderId: '106580139327',
    projectId: 'therapy-app-9d5f9',
    storageBucket: 'therapy-app-9d5f9.firebasestorage.app',
    iosBundleId: 'com.example.therapy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOmID1iif-2V00x3FRoILbvd92DJFJBFs',
    appId: '1:106580139327:ios:3373c22a68bc279d3bc78a',
    messagingSenderId: '106580139327',
    projectId: 'therapy-app-9d5f9',
    storageBucket: 'therapy-app-9d5f9.firebasestorage.app',
    iosBundleId: 'com.example.therapy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqTt-6GbaSbXOJ_U9PtiEYMHlo5W5RtjA',
    appId: '1:106580139327:web:c08710c327aa46dc3bc78a',
    messagingSenderId: '106580139327',
    projectId: 'therapy-app-9d5f9',
    authDomain: 'therapy-app-9d5f9.firebaseapp.com',
    storageBucket: 'therapy-app-9d5f9.firebasestorage.app',
    measurementId: 'G-Y59KZFHKSQ',
  );
}
